### ISSUE TITLE
`IfConditionalRule` should prevent identity comparison of objects by default (with ability to whitelist certain classes)

### ISSUE THREAD

**Issue by ZebulanStanphill** [voku/phpstan-rules#17]
#### What is this feature about (expected vs actual behaviour)?

`IfConditionalRule` does not prevent comparing objects using the identity comparison operator (`===`). And to some extent, this makes sense, since that's the only comparison operator that is actually useful for objects.

However, more often than not (in my experience), whenever I end up using this operator, it's a mistake on my part, because I'm trying to compare two objects that implement [`Ds\Hashable`](https://www.php.net/manual/en/class.ds-hashable.php), and I forget that the way to do that is via the [`equals` method](https://www.php.net/manual/en/ds-hashable.equals.php), since PHP lacks operator overloading (for better or worse).

I think it would be a good idea to prevent this sort of thing by default, but add the ability to whitelist comparing certain classes by identity.

#### How can I reproduce it?

```php
<?php declare(strict_types=1);
namespace Foo\Bar;

final class MyId implements \Ds\Hashable {
	public function __construct(public string $value) {}

	/** @throws \InvalidArgumentException */
	public function equals($otherObj): bool {
		if (!($otherObj instanceof static)) {
			throw new \InvalidArgumentException();
		}
		return $this->hash() === $otherObj->hash();
	}

	public function hash(): string { return $this->value; }
}

function doStuff(MyId $idA, MyId $idB): bool {
	// This is a logical error; it should have been $idA->equals($idB)
	return $idA === $idB;
}
```

No error is currently reported for this.

#### Does it take minutes, hours or days to fix?

There's already code for a similar whitelist (`classesNotInIfConditions`), so I assume adding another wouldn't be too difficult. So hours, I guess?

**Comment by voku** [comment]
Have you already tried the "classesNotInIfConditions" setting as written in the README file. Maybe it's everything that you need? 🤔

**Comment by ZebulanStanphill** [comment]
Oh, I thought that if I didn't set that list, it would just default to blocking all objects from being compared, regardless of class. But it turns out that's not the case. Is that intentional? Is the default behavior supposed to be allowing all classes to be compared?

Either way, it turns out that the issue I reported here doesn't actually exist. Thanks!

**Comment by voku** [comment]
I developed that check, when I introduced ValueObjects in our codebase and I needed to check all conditions of this properties in a >= 10.000 classes project. So, yes it's working as expected (at least) for my use-case. 😁
